version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # C++ Engine
  cpp-engine:
    build: ./cpp-engine
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  # ML Engine
  ml-engine:
    build: ./ml-engine
    ports:
      - "5001:5001"

  # Backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/billing-engine
      - JWT_SECRET=your_super_secret_key_here
      - CPP_ENGINE_URL=http://cpp-engine:8080
      - ML_ENGINE_URL=http://ml-engine:5001
      - PORT=5000
    depends_on:
      - mongodb
      - cpp-engine
      - ml-engine

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # ✅ MinIO (ADD THIS PART)
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

volumes:
  mongo_data: